# Generated by Django 3.1.1 on 2020-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200909_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_number',
            field=models.IntegerField(default=0),
        ),
    ]
