# Generated by Django 3.1.1 on 2020-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_actor_actor_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
